apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: library-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
      - name: backend
        image: mohamedessam1911/library-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/library"

